// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/airselfy/Album.tsx": () => import("../components/mockups/airselfy/Album.tsx"),
  "./components/mockups/airselfy/Camera.tsx": () => import("../components/mockups/airselfy/Camera.tsx"),
  "./components/mockups/airselfy/Compass.tsx": () => import("../components/mockups/airselfy/Compass.tsx"),
  "./components/mockups/airselfy/CreateAccount.tsx": () => import("../components/mockups/airselfy/CreateAccount.tsx"),
  "./components/mockups/airselfy/Home.tsx": () => import("../components/mockups/airselfy/Home.tsx"),
  "./components/mockups/airselfy/Login.tsx": () => import("../components/mockups/airselfy/Login.tsx"),
  "./components/mockups/airselfy/Map.tsx": () => import("../components/mockups/airselfy/Map.tsx")
};
