kind = "mobile"
previewPath = "/airselfy/"
title = "Airselfy"
version = "1.0.0"
id = "artifacts/airselfy"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/airselfy/" ]
localPort = 22899

[services.development]
run = "npm run dev --workspace=@workspace/airselfy"

[services.production]
build = [ "npm", "run", "build", "--workspace=@workspace/airselfy" ]
run = [ "npm", "run", "serve", "--workspace=@workspace/airselfy" ]

[services.env]
PORT = "22899"
BASE_PATH = "/airselfy/"
