kind = "mobile"
previewPath = "/airselfy/"
title = "Airselfy"
version = "1.0.0"
id = "artifacts/airselfy"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/airselfy/" ]
localPort = 22899

[services.development]
run = "pnpm --filter @workspace/airselfy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/airselfy", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/airselfy", "run", "serve" ]

[services.env]
PORT = "22899"
BASE_PATH = "/airselfy/"
